-- Cogent hot tier — narrow table, no full content columns.
-- Only metadata, previews, refs, sizes. Rows are predictably small.
CREATE TABLE IF NOT EXISTS agent_telemetry (
  ts                       TimestampMillisecond NOT NULL,
  trace_id                 STRING,
  span_id                  STRING,
  parent_span_id           STRING,
  start_time               DOUBLE,
  end_time                 DOUBLE,
  duration_ms              DOUBLE,
  agent_name               STRING,
  operation                STRING,
  service_name             STRING,
  environment              STRING,
  model                    STRING,
  provider                 STRING,
  input_tokens             INT32,
  output_tokens            INT32,
  cost_usd                 DOUBLE,
  finish_reason            STRING,
  prompt_preview           STRING,
  prompt_ref               STRING,
  prompt_size_bytes        INT64,
  completion_preview       STRING,
  completion_ref           STRING,
  completion_size_bytes    INT64,
  tool_name                STRING,
  tool_input_preview       STRING,
  tool_input_ref           STRING,
  tool_input_size_bytes    INT64,
  tool_output_preview      STRING,
  tool_output_ref          STRING,
  tool_output_size_bytes   INT64,
  tool_error               STRING,
  eval_score               DOUBLE,
  eval_label               STRING,
  eval_source              STRING,
  PRIMARY KEY (agent_name, operation, trace_id, span_id),
  TIME INDEX (ts)
);
